#!/bin/bash

VER=$1

if [ -z $VER ]; then
  VER=$(ls /usr/lib/modules | cut -d ' ' -f 1)
fi

IMG_FILE=$(mktemp)
tinyramfs -f -k $VER $IMG_FILE

VMLINUZ=$(ls /usr/lib/modules/*/vmlinuz)
mkdir -p /boot/EFI/BOOT

binutils-objcopy \
  --add-section .osrel=/etc/os-release --change-section-vma .osrel=0x20000 \
  --add-section .cmdline=/etc/kernel/cmdline --change-section-vma .cmdline=0x30000 \
  --add-section .linux=${VMLINUZ} --change-section-vma .linux=0x2000000 \
  --add-section .initrd=$IMG_FILE --change-section-vma .initrd=0x3000000 \
  /usr/share/efistub/efi.stub /boot/EFI/BOOT/BOOTX64.EFI

rm $IMG_FILE
